# Generated by Django 5.0.1 on 2024-01-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_branch_car_employee_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='place',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
